baseurl = "hagemon.github.com"
languageCode = "zh-cn"
Title = "Hagemon's Log"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Hagemon Production"

# enable get info from git commits, such as file modification time.
# so we don't have to manually update it.
enableGitInfo = true

[params]
  paginate = 10

  # Hide the date on posts
  # hideDate = true
  # Hide last modified date on posts
  # hideModifiedDate = true
  # Hide the word count on posts and in the posts list
  hideWordCount = true
  # Hide the reading time on posts and in the posts list
  hideReadingTime = true
  custom_css = ["/css/custom.css"]
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "禿禿怪"
  github = "hagemon"
  # Disqus shortname
#   disqus = ""
#   author = "Your Name"
#   avatar = "/static/favicon.ico"
#   contact = "ooonefolder@gmail.com"
#   bio = "CLEAN AND FREEDOM"
  # Short subtitle/tagline. This is displayed in the header.
#   subtitle = "Short subtitle"
  # Logo image. This is displayed ogp image.
  logo = "/static/favicon.ico"
  favicon = "/static/favicon.ico"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
