baseurl = "https://hagemon.github.io/"
languageCode = "zh-cn"
Title = "Hagemon's Log"
# Copyright notice. This is displayer in the footer.
copyright = "Hagemon Production"

theme = "hugo_theme_pickles"

# enable get info from git commits, such as file modification time.
# so we don't have to manually update it.
enableGitInfo = true

[params]
  paginate = 10
  hideWordCount = true
  hideReadingTime = true
  hideSummary = true
  hideModifiedDate = true
  twitter = "oneFolder_"
  github = "hagemon"
  custom_css = ["/css/custom.css"]
  favicon = "/favicon.ico"


[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
